add beta logger
AlmazDefourten/pears pull request #3
Opened 2022-11-14 18:53 UTC by GoshaV2

чекни добавил логер, там если что можно будет его на другой поменять

2022-11-14 22:58 UTC, AlmazDefourten requested changes
1) Неправильное ослабление зависимостей
2) Слабо пока с Go, подучи и отойди от привычек питона
3) Почитай про wire если хочешь возможность менять зависимость логгера (ослабление зависимости) и через него уже создавай объект логгера (сначала создается интерфейс, описываются методы которые применяются, делается отдельный файлик реализации логгера - логруса, он должен реализовывать интерфейс, в вайре биндится интерфейс к структуре логруса и возвращается либо интерфейс либо структура логгер)

2022-11-14 22:58 UTC, AlmazDefourten commented on appconfig.json
> +    "connection": "host=localhost port=5432 user=postgres password=admin dbname=postgres sslmode=disable",
этот файл не коммить никогда, я его еще в гитигнор не добавил, это пользовательские настройки приложения

2022-11-14 22:58 UTC, AlmazDefourten commented on logs/all.log
> +time="2022-11-14T18:02:51+03:00" level=info msg=start func="main.main()" file="app.go:13"
переименуй файл что-то типо global.logs, для сервисов будет отдельный services.logs

2022-11-14 22:58 UTC, AlmazDefourten commented on pkg/logging/logging.go
> +package logging
нет комментариев, код не самодокументируемый местами

2022-11-14 22:58 UTC, AlmazDefourten commented on pkg/logging/logging.go
> +func (hook *writerHook) Fire(entry *logrus.Entry) error {
Fire - что это?

2022-11-14 22:58 UTC, AlmazDefourten commented on pkg/logging/logging.go
> +var e *logrus.Entry
глобальная переменная, избавиться

2022-11-14 22:58 UTC, AlmazDefourten commented on pkg/logging/logging.go
> +type Logger struct {
структуры и геттеры объявляют обычно в начале файла

2022-11-14 22:58 UTC, AlmazDefourten commented on pkg/logging/logging.go
> +func init() {
ты тут я так понял делаешь структуру Logger для ослабления зависимости от реализации, но init() - означает инициализацию логгера как абстрактной модели по сути, ты же тут привязываешься к логрусу что зависимость не очень то и ослабляет, лучше сделать отдельный файл инициализации логруса и через wire инициализировать эту зависимость, init переделать в NewLogrus и оттащить в отдельный файл, вместо того чтоб в глобальную переменную записывать ты геттер убираешь и в мейне через wire достаешь этот логгер, возвращать эта функция должна будет Logger по сути который ты объявил если ты тут хочешь ослабить зависимость через нее, и сделать интерфейс к логгеру который будет этот логгер реализовывать, потом в wire забиндить этот интерфейс к структуре и NewLogrus забилдив (wire.Build) будешь получать твой экземпляр логгера, посмотри как я это реализовывал в wire.go

2022-11-14 22:58 UTC, AlmazDefourten commented on pkg/logging/logging.go
> +func init() {
NewLogrus - название если что для конструктора, почитай про соглашение именование конструкторов в Go, это не питон чтоб иниты прописывать, также для того чтоб функция была доступна вне модуля нужно с заглавной буквы функцию именовать (видимо из-за этого ты глобальную переменную и геттер ввел, лол)

2022-11-14 22:58 UTC, AlmazDefourten commented on pkg/logging/logging.go
> +	e = logrus.NewEntry(l)
бред, используй конструкторы, а лучше сначала изучи основы Go чтоб бесовскими делами не заниматься по типу записывания в глобальную переменную (мы пишем не скриптик на питоне, помни!)

2022-11-14 22:58 UTC, AlmazDefourten commented on pkg/logging/logging.go
> +	err := os.MkdirAll("logs", 0644)
0644 - магические числа, завести константу

2022-11-14 22:58 UTC, AlmazDefourten commented on pkg/logging/logging.go
> +	allFile, err := os.OpenFile("logs/all.log", os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0640)
0640 - магические числа, завести константу

2022-11-14 22:58 UTC, AlmazDefourten commented on pkg/logging/logging.go
> +	e = logrus.NewEntry(l)
1 - магические числа, завести константу

2022-11-14 22:58 UTC, AlmazDefourten commented on pkg/logging/logging.go
> +	l := logrus.New()
l - так переменную не именовать, читай самодокументируемый код и про правильное именования переменных

2022-11-14 22:58 UTC, AlmazDefourten commented on app.go
> +	logger := logging.GetLogger()
зависимость напрямую, завести интерфейс и внедрять через wire

2022-12-24 19:21 UTC, AlmazDefourten requested changes
на доработку, использовать wire и вместо параметров в стрингах использовать енумы (если енум такой-то - использовать такую-то константу стринг...)

2022-12-24 19:21 UTC, AlmazDefourten commented on container/DependenciesService.go
> +func NewLoggerContainer(nameOfDirLog string, nameOfNameLog string) logging.LoggerInterface {
теперь этот конструктор нужно зарегистрировать в wire, и уже через wire использовать, и еще это же не контейнер а просто конструктор, зачем контейнером обозвал

2022-12-24 19:21 UTC, AlmazDefourten commented on app.go
> +	//logger := logging.GetLoggerLorgus()
( к комменту о регистрации в wire) - вот тут как раз и используешь потом сгенерированный wire метод для получения логгера

2022-12-24 19:21 UTC, AlmazDefourten commented on logs/global.log
> +time="2022-11-14T18:02:51+03:00" level=info msg=start func="main.main()" file="app.go:13"
добавить файл в гитигнор

2022-12-24 19:21 UTC, AlmazDefourten commented on logs/global.log
> +time="2022-11-14T18:02:51+03:00" level=info msg=start func="main.main()" file="app.go:13"
(после того как зальешь его пустым)

2022-12-24 19:21 UTC, AlmazDefourten commented on pkg/logging/logger.go
> +func GetInstanceLogger(nameOfLogDir string, nameOfLog string) LoggerInterface {
я так понял ты тут строки как разделение на сервисный логгер и глобальный используешь - затея максимально странная, использовать enum

2022-12-30 08:53 UTC, AlmazDefourten requested changes
wire using

2023-01-06 11:11 UTC, AlmazDefourten requested changes
недочеты в чистоте кода

2023-01-06 11:11 UTC, AlmazDefourten commented on container/DependenciesService.go
> +func NewLoggerLogrus(typeLogger logging.TypeLogger) logging.LoggerInterface {
кароч я тут подумал это все нужно отрефакторить... запуливай так, это не трогай, я потом сделаю

2023-01-07 10:00 UTC, AlmazDefourten requested changes

2023-01-26 16:06 UTC, AlmazDefourten requested changes
good, but some problems with abstractions and wire usings

2023-01-26 16:06 UTC, AlmazDefourten commented on pkg/logging/logger.go
> +func (loggerPathHelper *LoggerPathUtil) GetPath() (*PathLogger, error) {
vinesti v otdelniy fail - loggerResolver naprimer obozvat, interface vinesti v modeli - eto ne third-part-vesh, realizaciu loggera ostavlyaesh tutm loggerReslover tozhe v project vinoshich a ne v pkg ostavlaesh, v pkg u tebya tolko realizacia loggera dolshna bit

2023-01-26 16:06 UTC, AlmazDefourten commented on wire.go
> +func InitLogrusLogger(typeLogger logging.TypeLogger) logging.Logger {
good

2023-01-26 16:06 UTC, AlmazDefourten commented on wire.go
> +func InitLogrusLogger(typeLogger logging.TypeLogger) logging.Logger {
no dolzhno bit wire.Build i wire.Bind, a ne return prostoi

2023-01-26 16:06 UTC, AlmazDefourten commented on wire.go
> +func InitLogrusLogger(typeLogger logging.TypeLogger) logging.Logger {
typeLogger avtomatom podtyanetsa, vosvrashaesh ti prosto structuru ili interface ne pomnyu, avtumaticheski chto sbilditsa v wire.Build vozvratitsa vmesto etogo

2023-01-27 21:24 UTC, GoshaV2 commented on wire.go
> +func InitLogrusLogger(typeLogger logging.TypeLogger) logging.Logger {
Да здесь, с возращаемым значением ошибся, а про wire.Bind не очень понял

2023-01-28 06:35 UTC, AlmazDefourten approved these changes
под сомнениями мерж, но ладно, пробуем

2023-01-28 06:35 UTC, merged